### ISSUE TITLE
Iredmail docker process not working

### ISSUE THREAD

**Issue by sim-dkk** [iredmail/dockerized#92] opened 2021-12-21 00:55 UTC
Hi 
Have many days on and off trying to get docker to work with iredmail . More then 30 hours investigatingf

There seems to be bad configure error with the docker contianer created .

1.  Mariadb is randomly creatly long passwords on the fly for all of the msyql user accounts which are 'user'@'%'
2.  The actual created live mysql passwords can be found in /var/lib/docker/overlay2/xxx/merged/root/.my...     
      where xxx is the docker container hash id .
3.   Postfix smtp mail server does not work because the password stored in the files in the folder 
      /var/lib/docker/overlay2/xxx/merged/etc/postfix/mysql/  
     do not match the mysql created passwords .

4.   The configuration directive  **MYSQL_USE_RANDOM_PASSWORDS=NO**  made no difference.

Please advise how to fix this as this hard error in the base of iredmail .

**Comment by sim-dkk** [comment] 2021-12-21 00:55
I have created the following bash script which will automaticaly create the docker instance

**Comment by sim-dkk** [comment] 2021-12-21 00:56
#!/bin/sh
#
# ----------------------------------------------------------------------------------------
#
# Creates IredMail instance .  !!!  Must be run as real root !!!
#
# ----------------------------------------------------------------------------------------
# Useful docker commands
#
#  Delete all docker instance from the system 			:  	docker system prune -a                      
#  lists all docker containers 							:  	docker container ls -a                     
#  Start the iredmail docker service 					:  	docker start iredmail
#  Stop the iredmail docker service 					:  	docker stop iredmail
#  Restart the iredmail docker service 					:  	docker restart iredmail
#  Get shell access into the iredmail docker instance 	:	docker exec -it iredmail bash 
#
#  Search for files inside the docker instance example	:   find /var/lib/docker/* |grep 'mail.log'
#
#  Search for the create setting for the iredmail 		:	cat $(find /var/lib/docker/* |grep 'iRedMail.tips' |grep 'merged')
#  system once the docker instance is created 10 minutes
#  after running the install commands 
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# create the directory just in case it has been deleted
mkdir /var/lib/docker/overlay2/l 
# ----------------------------------------------------------------------------------------
# Create a new directory or use any directory  
# you prefer. `/iredmail/` is just an example
mkdir /srv
mkdir /srv/iredmail         
rm -rf /srv/iredmail/* 
cd /srv/iredmail
touch iredmail-docker.conf
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Ired mail settings for the install script
#
server_ip_add="xxx.xxx.xxx.xxx"
server_hostname="hostname.com"
postmaster_pwd="your_pwd_12345576"
MYSQL_ROOT_PWD="your_pwd_4_msql_9854298629"

# ----------------------------------------------------------------------------------------
# These dns servers are Quad9 dns servers which automatically block a lot of 
# bad actors resolving dns  from bad places. 
# 
#  Big Plus Quad9 dns servers are cover by Swiss law and USA law................
#
#  Might not work if your server is in china then you have use a different set of dns server. 
DNS_Server_1="9.9.9.9"
DNS_Server_2="149.112.112.112"
#
# Ref
#		https://en.wikipedia.org/wiki/Quad9

# ----------------------------------------------------------------------------------------
#
# Find local Timezone by looking here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#
Time_zone="Europe/Dublin"
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# text correction  , formating the text for the docker instance creation 
#
Time_zone_full='"TZ='$Time_zone'"'
Post_pwd_full='"POSTMASTER_PASSWORD={PLAIN}'$postmaster_pwd'"'
mysql_root_pwd_full='"MYSQL_ROOT_PASSWORD='$MYSQL_ROOT_PWD'"'
DNS_Server_1_full='"'$DNS_Server_1'"'
DNS_Server_2_full='"'$DNS_Server_2'"'
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Save Customisation setting to the iredmail-docker.conf
# 
#  See https://github.com/iredmail/dockerized/blob/master/settings.conf  for 
#  guidance of what settings you can hard set 
#
#  it is strongly suggested you do not use  MYSQL_USE_RANDOM_PASSWORDS=YES 
#  as this setting is not working and then your iredmail instance will not work
#  as the mail system can not talk to the back end mysql db as they not do not
#  matching passwords. 
#
echo HOSTNAME=mail.$server_hostname >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN=$server_hostname >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=$postmaster_pwd >> iredmail-docker.conf
echo MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32) >> iredmail-docker.conf
echo ROUNDCUBE_DES_KEY=$(openssl rand -base64 24) >> iredmail-docker.conf
echo MYSQL_USE_RANDOM_PASSWORDS=NO >> iredmail-docker.conf
echo VMAIL_DB_ADMIN_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo AMAVISD_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo ROUNDCUBE_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo IREDAPD_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo IREDADMIN_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo FAIL2BAN_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo SA_BAYES_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo USE_SOGO=YES >> iredmail-docker.conf
echo SOGO_WORKERS=5 >> iredmail-docker.conf
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------------------
# Docker commit shell turns the run instance into a real docker container
#
#  	This creates a parallel process which will create the  iredmail container 
#  	as permanent docker container called iredmail 
#
#   System waits 10 minutes before creating   
#
rm -rf docker_container_create.sh
echo '#!/bin/sh' >docker_container_create.sh
echo sleep 600  >> docker_container_create.sh
echo  docker commit iredmail iredmail/mariadb:stable >> docker_container_create.sh
echo  docker stop iredmail >> docker_container_create.sh
echo  sleep 5 >> docker_container_create.sh
echo  docker start iredmail >> docker_container_create.sh
#
chmod 755 ./docker_container_create.sh
nohup  /srv/iredmail/docker_container_create.sh >/dev/null 2>&1 &
# ----------------------------------------------------------------------------------------
rm -rf ./docker_cm.sh
touch ./docker_cm.sh
chmod 755 ./docker_cm.sh
echo 'docker run --privileged -ti\' >> docker_cm.sh
echo '   --name iredmail\' >> docker_cm.sh
echo '   --env-file /srv/iredmail/iredmail-docker.conf\' >> docker_cm.sh
echo '   -p '$server_ip_add':80:80 -p '$server_ip_add':443:443 -p '$server_ip_add':995:995 -p '$server_ip_add':993:993 -p '$server_ip_add':465:465 -p '$server_ip_add':587:587 -p '$server_ip_add':25:25\' >> docker_cm.sh
echo '   --add-host mail.'$server_hostname':127.0.0.1\' >> docker_cm.sh
echo '   --add-host mail:127.0.0.1\' >> docker_cm.sh
echo '   -h '$server_hostname' --ip '$server_ip_add'\' >> docker_cm.sh
echo '   -e '$mysql_root_pwd_full'\' >> docker_cm.sh
echo '   --dns='$DNS_Server_1_full'\' >> docker_cm.sh
echo '   --dns='$DNS_Server_2_full'\' >> docker_cm.sh
echo '   -e '$Time_zone_full'\' >> docker_cm.sh
echo '   -e '$Post_pwd_full'\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/backup-mysql:/var/vmail/backup/mysql\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mailboxes:/var/vmail/vmail1\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mlmmj:/var/vmail/mlmmj\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/custom:/opt/iredmail/custom\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/ssl:/opt/iredmail/ssl\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mysql:/var/lib/mysql\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/clamav:/var/lib/clamav\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/sa_rules:/var/lib/spamassassin\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/postfix_queue:/var/spool/postfix\' >> docker_cm.sh
echo '   iredmail/mariadb:stable' >> docker_cm.sh
#
# Execute the docker container instance creation shell 
#	
/srv/iredmail/docker_cm.sh

**Comment by sim-dkk** [comment] 2021-12-21 00:58
#!/bin/sh
#
# ----------------------------------------------------------------------------------------
#
# Creates IredMail instance .  !!!  Must be run as real root !!!
#
# ----------------------------------------------------------------------------------------
# Useful docker commands
#
#  Delete all docker instance from the system 			:  	docker system prune -a                      
#  lists all docker containers 							:  	docker container ls -a                     
#  Start the iredmail docker service 					:  	docker start iredmail
#  Stop the iredmail docker service 					:  	docker stop iredmail
#  Restart the iredmail docker service 					:  	docker restart iredmail
#  Get shell access into the iredmail docker instance 	:	docker exec -it iredmail bash 
#
#  Search for files inside the docker instance example	:   find /var/lib/docker/* |grep 'mail.log'
#
#  Search for the create setting for the iredmail 		:	cat $(find /var/lib/docker/* |grep 'iRedMail.tips' |grep 'merged')
#  system once the docker instance is created 10 minutes
#  after running the install commands 
# ----------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------
# create the directory just in case it has been deleted
mkdir /var/lib/docker/overlay2/l 
# ----------------------------------------------------------------------------------------
# Create a new directory or use any directory  
# you prefer. `/iredmail/` is just an example
mkdir /srv
mkdir /srv/iredmail         
rm -rf /srv/iredmail/* 
cd /srv/iredmail
touch iredmail-docker.conf
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Ired mail settings for the install script
#
server_ip_add="xxx.xxx.xxx.xxx"
server_hostname="hostname.com"
postmaster_pwd="your_pwd_12345576"
MYSQL_ROOT_PWD="your_pwd_4_msql_9854298629"

# ----------------------------------------------------------------------------------------
# These dns servers are Quad9 dns servers which automatically block a lot of 
# bad actors resolving dns  from bad places. 
# 
#  Big Plus Quad9 dns servers are cover by Swiss law and USA law................
#
#  Might not work if your server is in china then you have use a different set of dns server. 
DNS_Server_1="9.9.9.9"
DNS_Server_2="149.112.112.112"
#
# Ref
#		https://en.wikipedia.org/wiki/Quad9

# ----------------------------------------------------------------------------------------
#
# Find local Timezone by looking here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#
Time_zone="Europe/Dublin"
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# text correction  , formating the text for the docker instance creation 
#
Time_zone_full='"TZ='$Time_zone'"'
Post_pwd_full='"POSTMASTER_PASSWORD={PLAIN}'$postmaster_pwd'"'
mysql_root_pwd_full='"MYSQL_ROOT_PASSWORD='$MYSQL_ROOT_PWD'"'
DNS_Server_1_full='"'$DNS_Server_1'"'
DNS_Server_2_full='"'$DNS_Server_2'"'
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# Save Customisation setting to the iredmail-docker.conf
# 
#  See https://github.com/iredmail/dockerized/blob/master/settings.conf  for 
#  guidance of what settings you can hard set 
#
#  it is strongly suggested you do not use  MYSQL_USE_RANDOM_PASSWORDS=YES 
#  as this setting is not working and then your iredmail instance will not work
#  as the mail system can not talk to the back end mysql db as they not do not
#  matching passwords. 
#
echo HOSTNAME=mail.$server_hostname >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN=$server_hostname >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=$postmaster_pwd >> iredmail-docker.conf
echo MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32) >> iredmail-docker.conf
echo ROUNDCUBE_DES_KEY=$(openssl rand -base64 24) >> iredmail-docker.conf
echo MYSQL_USE_RANDOM_PASSWORDS=NO >> iredmail-docker.conf
echo VMAIL_DB_ADMIN_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo AMAVISD_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo ROUNDCUBE_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo IREDAPD_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo IREDADMIN_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo FAIL2BAN_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo SA_BAYES_DB_PASSWORD=$(openssl rand -base64 30) >> iredmail-docker.conf
echo USE_SOGO=YES >> iredmail-docker.conf
echo SOGO_WORKERS=5 >> iredmail-docker.conf
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
#
# ----------------------------------------------------------------------------------------
# Docker commit shell turns the run instance into a real docker container
#
#  	This creates a parallel process which will create the  iredmail container 
#  	as permanent docker container called iredmail 
#
#   System waits 10 minutes before creating   
#
rm -rf docker_container_create.sh
echo '#!/bin/sh' >docker_container_create.sh
echo sleep 600  >> docker_container_create.sh
echo  docker commit iredmail iredmail/mariadb:stable >> docker_container_create.sh
echo  docker stop iredmail >> docker_container_create.sh
echo  sleep 5 >> docker_container_create.sh
echo  docker start iredmail >> docker_container_create.sh
#
chmod 755 ./docker_container_create.sh
nohup  /srv/iredmail/docker_container_create.sh >/dev/null 2>&1 &
# ----------------------------------------------------------------------------------------
rm -rf ./docker_cm.sh
touch ./docker_cm.sh
chmod 755 ./docker_cm.sh
echo 'docker run --privileged -ti\' >> docker_cm.sh
echo '   --name iredmail\' >> docker_cm.sh
echo '   --env-file /srv/iredmail/iredmail-docker.conf\' >> docker_cm.sh
echo '   -p '$server_ip_add':80:80 -p '$server_ip_add':443:443 -p '$server_ip_add':995:995 -p '$server_ip_add':993:993 -p '$server_ip_add':465:465 -p '$server_ip_add':587:587 -p '$server_ip_add':25:25\' >> docker_cm.sh
echo '   --add-host mail.'$server_hostname':127.0.0.1\' >> docker_cm.sh
echo '   --add-host mail:127.0.0.1\' >> docker_cm.sh
echo '   -h '$server_hostname' --ip '$server_ip_add'\' >> docker_cm.sh
echo '   -e '$mysql_root_pwd_full'\' >> docker_cm.sh
echo '   --dns='$DNS_Server_1_full'\' >> docker_cm.sh
echo '   --dns='$DNS_Server_2_full'\' >> docker_cm.sh
echo '   -e '$Time_zone_full'\' >> docker_cm.sh
echo '   -e '$Post_pwd_full'\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/backup-mysql:/var/vmail/backup/mysql\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mailboxes:/var/vmail/vmail1\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mlmmj:/var/vmail/mlmmj\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/custom:/opt/iredmail/custom\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/ssl:/opt/iredmail/ssl\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/mysql:/var/lib/mysql\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/clamav:/var/lib/clamav\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/sa_rules:/var/lib/spamassassin\' >> docker_cm.sh
echo '   -v /srv/iredmail/data/postfix_queue:/var/spool/postfix\' >> docker_cm.sh
echo '   iredmail/mariadb:stable' >> docker_cm.sh
#
# Execute the docker container instance creation shell 
#	
/srv/iredmail/docker_cm.sh

**Comment by sim-dkk** [comment] 2021-12-21 01:05
[Iredmail_install_v2_internet_version.txt](https://github.com/iredmail/dockerized/files/7748813/Iredmail_install_v2_internet_version.txt)

**Comment by sim-dkk** [comment] 2021-12-21 01:07
The script runs and creates a iredmail docker instance once the user has set the following things up 
** Ired mail settings for the install script**

server_ip_add="xxx.xxx.xxx.xxx"
server_hostname="hostname.com"
postmaster_pwd="your_pwd_12345576"
MYSQL_ROOT_PWD="your_pwd_4_msql_9854298629"

**Comment by sim-dkk** [comment] 2021-12-21 01:13
Once the iredmail is up and running it does not fully work due to the issue of the postfix/smtp server not being able to access the mariadb database using the mysql username vmail because the password issue described above. 

Please advise how to fix this is this a really core setup isssue with iredmail and not easy to fix unless I spend many days and hours learning the insides of iredmail .

**Comment by iredmail** [comment] 2021-12-21 01:23
Sorry about this trouble, I will try to test the latest nightly build later today.

**Comment by sim-dkk** [comment] 2021-12-29 15:56
Hi 
Any luck in finding the issue and fixing it ?
Best wishes 
Simon

**Comment by sim-dkk** [comment] 2021-12-29 15:58
I suggest you try the script which I added to this thread , this automates the whole install process . 
 You welcome to use it on your github page 

All it would need is a curl statement to pull down and use it on users unix platform

**Comment by sim-dkk** [comment] 2021-12-30 14:39
Hi . Just tested again by creating a new fresh install instance on docker  with the script . There is still the issue as described above.

**Comment by iredmail** [comment] 2021-12-30 14:47
hmm, i'm considering maybe we should stop spending time on this docker edition.

**Comment by sim-dkk** [comment] 2021-12-30 22:52
Hi 
If show me where to look I can fix the issue . The reason I did not fix the isssue was I could not see myt way through yoru code and the way docker pull file modules together.  You have set up iredemail some where that it a script auto generates new mysql pwd at each docker container start up but these passwords are not copied over into the other setting folder.

it looks a like a classic bit of bash script is need to which fixes the issue .  

The key issue is finding the source auto generates new mysql pwd at boot or on cron job timer .. 

Then we have the over lay of docker doing also weird settings activities.

Look forward to hearing from you with your throughts ..

**Comment by bluepuma77** [comment] 2022-01-06 13:38
> hmm, i'm considering maybe we should stop spending time on this docker edition.

@iredmail I believe everything is moving to containers, so that might be a bad move if you want to stay relevant.

I had [extensive issues](https://github.com/iredmail/dockerized/issues/88) with an older version of iRedMail with partly new generated passwords, I had to manually go into the container and change them back.

I think just the password-generation needs to be improved a little.

**Comment by iredmail** [comment] 2022-01-06 13:44
- Container is better for a single-application situation, but this is an all-in-one container. hmm
- I will take a look at the random password issue later. PR is welcome.

**Comment by sabloger** [comment] 2022-02-19 12:01
Hello everyone, 
I have been struggling with the same problem last days, I tried many solutions and finally seems like I found the fix.
As y'all know the problem is with the random password-generator and the temporary fix is setting all *_DB_PASSWORD variables in the env_file (iredmail-docker.conf):
```
VMAIL_DB_PASSWORD=<secret>
VMAIL_DB_ADMIN_PASSWORD=<secret>
AMAVISD_DB_PASSWORD=<secret>
ROUNDCUBE_DB_PASSWORD=<secret>
IREDAPD_DB_PASSWORD=<secret>
IREDADMIN_DB_PASSWORD=<secret>
FAIL2BAN_DB_PASSWORD=<secret>
SA_BAYES_DB_PASSWORD=<secret>
```
* Note: I didn't set the MYSQL_ROOT_PASSWORD because I had run the container once before so technically the root password must not change.
** Note: To make this work, The current container must be removed and run again, but you can run it mounted to previously generated `data` directory.

I tested it with many times of docker restart and no problem has appeared again.

Hopefully in a good time I can make a PR for this problem too.

**Comment by sim-dkk** [comment] 2022-02-27 13:32
Hi 
Thank you to the team of reviewers on here and the work from the iredmail team using github .
it now works straight out of the box .

Enclosed is a full shell scrip that will run on centos system and set up a full email server system as a docker instance. 

Especial thanks to Sabloger for his work . 
[Iredmail_install_v5_version.txt](https://github.com/iredmail/dockerized/files/8148720/Iredmail_install_v5_version.txt)

This script was tested 27Feb2022 and created a fully working docker instance which is up and running

if you need to modifying this like the ssl certificate I suggest you the windows tool winscp it is by the far the best 
windows tool to access file systems on unix boxes 

Good luck and l hope you have lots fun 

Now I can say good by to the awful email provide lycos.com

**Comment by sim-dkk** [comment] 2022-02-27 13:35
I would suggest to iredmail github team that you take my script and use as the main install script . it works straight out of the box without lots of fiddling .  You can use free of charge without any copyright or Interlectuall property writes claim . It is free beer open source .

**Comment by iredmail** [comment] 2022-02-27 13:50
Thanks for the feedback and sharing. :)

**Closed by iredmail** 2022-02-27 13:50 UTC
