### ISSUE TITLE
Installation broken with latest changes

### ISSUE THREAD

**Issue by Markoftw** [iredmail/dockerized#55] opened 2021-04-21 14:31 UTC
Installation / startup seems to be stuck with /docker/entrypoints/mlmmjadmin.sh, over an hour there now.

I have tested it on a fresh Debian installation as well, stuck there too.

Using the instructions from the docker hub.

![image](https://user-images.githubusercontent.com/1616694/115568855-f9986e80-a2bc-11eb-8579-b3c5340bfc51.png)

**Comment by iredmail** [comment] 2021-04-21 14:44
I cannot reproduce this issue locally, the image runs well. :)

**Comment by Markoftw** [comment] 2021-04-21 15:03
If I'm not mistaken that's not the last step that should in the logs? Tried multiple times, deleted images, rebooted, ..., the same part gets stuck, even bash'd into the container and port 80 and 443 were not in use. 🤷

![image](https://user-images.githubusercontent.com/1616694/115575914-4d0dbb00-a2c3-11eb-8e38-85d067ec420a.png)

Using Docker v20.10.6 on Ubuntu 20.04.2 LTS

**Comment by hkasur** [comment] 2021-04-21 18:16
I ran into the same problem and it looks like it hangs on the mail command in [tip_file.sh](https://github.com/iredmail/dockerized/blob/93645cc23f9822fc1ee8e673e483d1d6b6c571d2/entrypoints/tip_file.sh#L16). The container boots up without issues now after adding `MAIL_THE_TIP_FILE=NO` to my local iredmail-docker.conf file.

**Comment by Markoftw** [comment] 2021-04-21 19:01
Seems you're right, boots up successfully after adding that parameter. Thanks for the tip!

**Comment by iredmail** [comment] 2021-04-22 01:23
Interesting, it works fine locally without `MAIL_THE_TIP_FILE=NO`.
I'm investigating this issue.

**Comment by iredmail** [comment] 2021-04-22 01:30
Should be fixed with last commit:
https://github.com/iredmail/dockerized/commit/05a77c4e2b7f0ea8141001c51b96e957d8347da9

Could you guys help test when the new image is available on Docker Hub?
https://hub.docker.com/r/iredmail/mariadb

**Comment by Markoftw** [comment] 2021-04-22 07:10
I can confirm it works without `MAIL_THE_TIP_FILE=NO`, received a tip email after successful boot. It can be closed.

**Comment by iredmail** [comment] 2021-04-22 09:12
Thanks for the help. :)

**Closed by iredmail** 2021-04-22 09:12 UTC

**Comment by bluepuma77** [comment] 2021-04-22 21:45
@iredmail Does not work for me using current `iredmail/mariadb:stable`.

 Container starts, logs stops with
```
[iRedMail] [Entrypoint] /docker/entrypoints/mlmmjadmin.sh
```
then I can't access any port. 

When ssh'ing into the container and using "ps -elf", I see

```
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root         1     0  0  80   0 -  1058 -      21:30 ?        00:00:00 /bin/bash /entrypoint.sh /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
4 S root       620     1  0  80   0 -  8006 -      21:31 ?        00:00:00 mail -s Details of this iRedMail container postmaster@domain.tld
0 S root       621   620  0  80   0 -  9507 -      21:31 ?        00:00:00 /usr/sbin/sendmail -oi -f root@domain.tld -t
4 S root       622   621  0  80   0 -  9504 -      21:31 ?        00:00:00 /usr/sbin/postdrop -r
4 S root       623     0  0  80   0 -  1061 -      21:33 pts/0    00:00:00 bash
0 R root       639   623  0  80   0 -  1475 -      21:34 pts/0    00:00:00 ps -elf
```

Only after I kill the mail process (620) the process continues.

For me this is reproducible on Debian when deleting all files and starting over.

The container only starts successfully when using `MAIL_THE_TIP_FILE=NO`.

**Comment by iredmail** [comment] 2021-04-23 02:13
ok, let's try to run the `mail -s ...` in background and not hang there.

Please help test when the new image is available on Docker Hub:
https://hub.docker.com/r/iredmail/mariadb

**Comment by bluepuma77** [comment] 2021-04-23 06:40
@iredmail Works for me now, thanks!

**Comment by iredmail** [comment] 2021-04-23 06:41
@bluepuma77 Great. Thanks for the feedback. :)

**Comment by bluepuma77** [comment] 2021-04-23 06:45
@iredmail Just an after-thought: maybe it did not work because I did not set --hostname to the full email domain.

**Comment by iredmail** [comment] 2021-04-23 06:46
@bluepuma77 Could be. but if it's resolvable, it should be fine.
