### ISSUE TITLE
Fails to send email after reboot. Lookup failure

### ISSUE THREAD

**Issue by GemzzK** [iredmail/dockerized#40] opened 2021-01-29 21:32 UTC
Hi,

After setting up if i reboot i get this message

![image](https://user-images.githubusercontent.com/67978637/106329147-97dce100-6246-11eb-9369-98d414154d05.png)

Further info

![image](https://user-images.githubusercontent.com/67978637/106329182-a4f9d000-6246-11eb-915c-830980ce212a.png)

![image](https://user-images.githubusercontent.com/67978637/106329269-c5298f00-6246-11eb-94f1-665349d93536.png)

**Comment by iredmail** [comment] 2021-01-30 03:45
Seems the SQL password set in /etc/postfix/mysql/*.cf is not correct, could you help check it?

**Comment by GemzzK** [comment] 2021-01-30 04:00
Yep let me know how i can check that. Lets fix this

**Comment by iredmail** [comment] 2021-01-30 04:04
After running the container, please login to the container and check the sql password in /etc/postfix/mysql/*.cf files, try to login to sql server with the sql username and password.

**Comment by GemzzK** [comment] 2021-01-30 04:23
Yep thats right. I fetched username and password but unable to login using that details.

**Comment by iredmail** [comment] 2021-01-30 05:18
Could you try the latest nightly build instead of stable one?

**Comment by GemzzK** [comment] 2021-01-30 16:44
i tried with latest nightly build but im getting this error 

![image](https://user-images.githubusercontent.com/67978637/106362381-4d418e80-6344-11eb-9705-05f54793d5e6.png)

**Comment by GemzzK** [comment] 2021-01-30 17:10
this is the error after latest nightly build

![image](https://user-images.githubusercontent.com/67978637/106363029-e1f9bb80-6347-11eb-8530-ca523e5f7c7a.png)

**Comment by iredmail** [comment] 2021-01-31 01:52
Confirmed it's an "issue" of Alpine 3.13.x: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12085
We need to switch from hash to lmdb. Stay tuned.

**Comment by iredmail** [comment] 2021-01-31 01:56
Maybe we should switch to Ubuntu 20.04 as base container, so that we get SOGo too.

**Comment by GemzzK** [comment] 2021-01-31 02:06
Switching to ubuntu will be good and will be stable. Alpine does push back in some scenarios.

**Comment by iredmail** [comment] 2021-02-07 12:24
Closing this since we're moving to Ubuntu (20.04) and don't have such issue anymore.

**Closed by iredmail** 2021-02-07 12:24 UTC
